### ISSUE TITLE
Installing KanboardCSS does not look right

### ISSUE THREAD

**Issue by FlyveHest** [aljawaid/KanboardCSS#17]
I've installed my first Kanboard today, and after getting that up and running I installed KanboardCSS and ColorManager, but I am pretty sure the results are not intended, the Task list looks all kinds of strange, as you can see below.

![image](https://user-images.githubusercontent.com/55623/218325204-7aa9ee5a-bc00-4634-bcf3-d94d2116c15d.png)

This is what it looks like without KanboardCSS enabled

![image](https://user-images.githubusercontent.com/55623/218325216-bf0ef5ed-266f-400a-89a2-170006126f74.png)

There are issues on other pages as well, with red bars above and below headers.

As mentioned, this is a completely fresh install of the latest versions of Kanboard, KanboardCSS and ColorManager.

**Comment by aljawaid** [comment]
Hello. This is all part of the design. The red bars etc. The theme is red and blue for this plugin.

**Comment by FlyveHest** [comment]
Oh, it just doesn't look like the screenshots on the frontpage at all, it might be a good idea to update those so expectations can be tempered. :)

Thanks for the quick answer though.

**Comment by aljawaid** [comment]
> Oh, it just doesn't look like the screenshots on the frontpage at all, it might be a good idea to update those so expectations can be tempered. :)
> 
> Thanks for the quick answer though.

Apologies for that. I use it on my live installation only so I need to blur out all the data for the screenshots. I've been heavily working on other Kanboard plugins which is why the screenshots are old.

KanboardCSS has advanced alot since the initial version. Give it a try. It works perfectly with ColorManager too, except on the board, I chose to keep the background colour as white and not the task colour to avoid distraction.

If you're new to Kanboard, I strongly suggest installing the PluginManager plugin before other plugins.

**Comment by marlov8** [comment]
I don't get it, why there is red note icon on cards, am I missing something?
